name: Release Candidate
on: 
  push:
    branches-ignore:
      - master
jobs:
  package:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        os: [ubuntu-18.04] # [ubuntu-18.04, [arm64,self-hosted,linux, build]]
      fail-fast: false
    steps:
      - uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v2
      - name: build
        uses: docker://ros-melodic
        run: build.sh
      - name: The generated package
        run: echo "The artifact is ${{ steps.package.outputs.artifact-path }}"
      - name: Deploy
        id: deploy
        uses: AutoModality/action-cloudsmith@0.2.0
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: 'deb'
          owner: 'automodality'
          repo: 'dev'
          distro: 'ubuntu'
          release: 'bionic'
          file: '${{ steps.package.outputs.artifact-path }}'
  draft-pr:
    runs-on: ubuntu-18.04
    needs: package
    steps:
      - uses: actions/checkout@v2
      - name: Draft a Pull Request
        uses: repo-sync/pull-request@v2
        with:
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
