name: Story Development

on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Cache 
        id: cache
        uses: actions/cache@v1
        with:
          path: obj-x86_64-linux-gnu
          key: pcl-cache
      - uses: actions/checkout@v2
      - name: Package
        id: package
        uses: AutoModality/action-package-debian-ros@v1.3.2