name: Story Development

on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/package@local
